<a href="https://colab.research.google.com/github/Sanjar-prog/Telegram-JavaScript-Bot/blob/main/Amaliyot_Kredit_berish_holatlarini_bashorat_qilish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Kerakli kutubxonalarni yuklab olamiz

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Processing

In [6]:
# Dataset'ni pandas Dataframe'ga yuklaymiz
loan_dataset = pd.read_csv('/housing_LR.csv')

In [7]:
type(loan_dataset)

pandas.core.frame.DataFrame

In [8]:
# Dataframe'ning dastlabki 5 qatorini chop etamiz
loan_dataset.head()

   Unnamed: 0       district  rooms  size  level  max_levels    price
0           0   Юнусабадский      3  57.0      4           4  52000.0
1           1  Яккасарайский      2  52.0      4           5  56000.0
2           2   Чиланзарский      2  42.0      4           4  37000.0
3           3   Чиланзарский      3  65.0      1           4  49500.0
4           4   Чиланзарский      3  70.0      3           5  55000.0

In [9]:
# Qatorlar va ustunlar soni
loan_dataset.shape

(7278, 7)

In [10]:
# Statistical measures
loan_dataset.describe()

,Unnamed: 0,rooms,size,level,max_levels,price
count,7278.000000,7278.000000,7278.00000,7278.000000,7278.000000,7278.000000
mean,3735.910552,2.578318,70.11898,3.689338,5.992718,54092.074196
std,2162.154719,1.030179,29.32120,2.228360,2.583194,29665.210900
min,0.000000,1.000000,1.00000,1.000000,1.000000,2.000000
25%,1862.250000,2.000000,50.00000,2.000000,4.000000,34800.000000
50%,3737.500000,2.000000,65.00000,3.000000,5.000000,45500.000000
75%,5611.750000,3.000000,83.00000,5.000000,9.000000,65000.000000
max,7464.000000,8.000000,279.00000,18.000000,25.000000,220000.000000

In [11]:
# Har bir ustunda yetishmayotgan qiymatlar
loan_dataset.isnull().sum()

Unnamed: 0    0
district      0
rooms         0
size          0
level         0
max_levels    0
price         0
dtype: int64

In [12]:
# Yetishmayotgan qiymatlarni o'chirish
loan_dataset = loan_dataset.dropna()

In [13]:
loan_dataset.isnull().sum()

Unnamed: 0    0
district      0
rooms         0
size          0
level         0
max_levels    0
price         0
dtype: int64

In [15]:
# Label encoding
loan_dataset.replace({"Loan_Status":{'N':0, 'Y':1}}, inplace=True)

In [16]:
# DataFrame'ning birinchi 5 qatorini chop etamiz
loan_dataset.head()

   Unnamed: 0       district  rooms  size  level  max_levels    price
0           0   Юнусабадский      3  57.0      4           4  52000.0
1           1  Яккасарайский      2  52.0      4           5  56000.0
2           2   Чиланзарский      2  42.0      4           4  37000.0
3           3   Чиланзарский      3  65.0      1           4  49500.0
4           4   Чиланзарский      3  70.0      3           5  55000.0

In [20]:
# Dependent ustun qiymatlari
loan_dataset['Dependents'].value_counts()

KeyError: 'Dependents'

In [21]:
# 3+ qiymatlarini 4 ga o'zgartiramiz
loan_dataset = loan_dataset.replace(to_replace='3+', value=4)

In [22]:
# Dependent qiymatlari
loan_dataset['Dependents'].value_counts()

KeyError: 'Dependents'

Data Visualization

In [28]:
# Education & Loan Status
sns.countplot(x="Education", hue="Loan_Status", data=loan_dataset)

ValueError: Could not interpret value `Education` for `x`. An entry with this name does not appear in `data`.

In [31]:
# Marital Status & Loan Status
sns.countplot(x='Married', hue='Loan_Status',data=loan_dataset)

ValueError: Could not interpret value `Married` for `x`. An entry with this name does not appear in `data`.

In [33]:
# Kategorik usutnlarni, raqamliga (numerical) o'zgartirish
loan_dataset.replace({'Married':{'No':0, 'Yes':1}, 'Gender':{'Male':1, 'Female':0}, 'Self_Empoyed':{'No':0, 'Yes':1}, 'Property_Area':{"Rural":0, 'Semiurban':1, 'Urban':2}, 'Education':{'Gradute':1, 'Not Gradute':0}}, inplace=True)

In [34]:
loan_dataset.head()

   Unnamed: 0       district  rooms  size  level  max_levels    price
0           0   Юнусабадский      3  57.0      4           4  52000.0
1           1  Яккасарайский      2  52.0      4           5  56000.0
2           2   Чиланзарский      2  42.0      4           4  37000.0
3           3   Чиланзарский      3  65.0      1           4  49500.0
4           4   Чиланзарский      3  70.0      3           5  55000.0

In [36]:
# Ma'lumotlarni ajratish va labellash
X = loan_dataset.drop(columns=['Loan_ID', 'Loan_Status'], axis=1)
Y = loan_dataset['Loan_Status']

KeyError: "['Loan_ID', 'Loan_Status'] not found in axis"

In [37]:
print(X)
print(Y)

NameError: name 'X' is not defined

In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, stratify=Y, random_state=2)

NameError: name 'X' is not defined

In [40]:
print(X.shape, X_train.shape, X_test.shape)

NameError: name 'X' is not defined

Training the Model:
Support Vector Machine Model

In [41]:
classifier = svm.SVC(kernel='linear')

In [45]:
# Support Vector Machine Model'ini Train qilish
classifier.fit(X_train, Y_train)

NameError: name 'X_train' is not defined

Model Evalution

In [46]:
# Training Data'ning accuracy score'i
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy score of the training data : ', training_data_accuracy)

NameError: name 'model' is not defined

In [47]:
print("Accuracy data score : ", Training_data_accuray)

NameError: name 'Training_data_accuray' is not defined

In [48]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

NameError: name 'model' is not defined

In [49]:
print("Accuracy data score : ", Test_data_accuray)

NameError: name 'Test_data_accuray' is not defined

In [50]:
# test Data'ning accuracy score'i