<a href="https://colab.research.google.com/github/Sanjar-prog/Telegram-JavaScript-Bot/blob/main/dropna()_NaN_qiymatlarni_tashlab_yuborish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [3]:
df.isnull()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,False,False,False,False,False,False,True,False,False
1,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...
81,False,False,False,False,False,False,False,False,False
82,False,False,True,False,True,False,False,False,False
86,False,False,False,True,False,False,False,True,False
87,False,False,False,False,True,False,False,False,False
88,False,False,False,False,False,False,True,False,False

In [4]:
df.notnull()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,True,True,True,True,True,True,False,True,True
1,True,True,False,True,True,True,True,True,True
2,True,True,True,True,True,True,True,False,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,False,False,True
...,...,...,...,...,...,...,...,...,...
81,True,True,True,True,True,True,True,True,True
82,True,True,False,True,False,True,True,True,True
86,True,True,True,False,True,True,True,False,True
87,True,True,True,True,False,True,True,True,True
88,True,True,True,True,True,True,False,True,True

In [5]:
df.isnull().sum()

company              0
body-style           0
wheel-base          15
length              13
engine-type         12
num-of-cylinders     0
horsepower          16
average-mileage     15
price                3
dtype: int64

In [6]:
len(df)

61

In [7]:
df.isnull().sum()/len(df)*100

company              0.000000
body-style           0.000000
wheel-base          24.590164
length              21.311475
engine-type         19.672131
num-of-cylinders     0.000000
horsepower          26.229508
average-mileage     24.590164
price                4.918033
dtype: float64

In [8]:
df.dropna()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0

In [9]:
len(df.dropna())

14

In [10]:
df.dropna(axis=1)

           company   body-style num-of-cylinders
index
0      alfa-romero  convertible             four
1      alfa-romero  convertible             four
2      alfa-romero    hatchback              six
3             audi        sedan             four
4             audi        sedan             five
...            ...          ...              ...
81      volkswagen        sedan             four
82      volkswagen        sedan             four
86      volkswagen        sedan             four
87           volvo        sedan             four
88           volvo        wagon             four

[61 rows x 3 columns]

In [11]:
df.dropna(axis=1, thresh=48, inplace=True)

In [12]:
df.dropna(subset=['price'])

,company,body-style,length,engine-type,num-of-cylinders,price
index,,,,,,
0,alfa-romero,convertible,168.8,dohc,four,13495.0
1,alfa-romero,convertible,168.8,dohc,four,16500.0
2,alfa-romero,hatchback,171.2,ohcv,six,16500.0
3,audi,sedan,176.6,ohc,four,13950.0
4,audi,sedan,176.6,ohc,five,17450.0
5,audi,sedan,177.3,ohc,five,15250.0
6,audi,wagon,192.7,ohc,five,18920.0
9,bmw,sedan,NaN,ohc,four,16430.0
10,bmw,sedan,176.8,ohc,four,16925.0
11,bmw,sedan,176.8,ohc,six,20970.0
13,bmw,sedan,189.0,ohc,six,30760.0
14,bmw,sedan,NaN,ohc,six,41315.0
15,bmw,sedan,197.0,ohc,six,36880.0
16,chevrolet,hatchback,141.1,l,three,5151.0
17,chevrolet,hatchback,155.9,ohc,four,6295.0
18,chevrolet,sedan,158.8,ohc,four,6575.0
19,dodge,hatchback,157.3,ohc,four,6377.0
20,dodge,hatchback,NaN,ohc,four,6229.0
27,honda,wagon,NaN,ohc,four,7295.0
28,honda,sedan,175.4,ohc,four,12945.0
29,honda,sedan,169.1,ohc,four,10345.0
30,isuzu,sedan,170.7,ohc,four,6785.0
33,jaguar,sedan,NaN,dohc,six,32250.0
34,jaguar,sedan,199.6,dohc,six,35550.0
35,jaguar,sedan,191.7,ohcv,twelve,36000.0
36,mazda,hatchback,159.1,NaN,four,5195.0
37,mazda,hatchback,159.1,ohc,four,6095.0
38,mazda,hatchback,159.1,ohc,four,6795.0
39,mazda,hatchback,NaN,NaN,two,11845.0
43,mazda,sedan,175.0,ohc,four,18344.0
44,mercedes-benz,sedan,190.9,NaN,five,25552.0
45,mercedes-benz,wagon,190.9,ohc,five,28248.0
46,mercedes-benz,sedan,208.1,NaN,eight,40960.0
47,mercedes-benz,hardtop,199.2,NaN,eight,45400.0
49,mitsubishi,hatchback,157.3,ohc,four,5389.0
50,mitsubishi,hatchback,NaN,NaN,four,6189.0
51,mitsubishi,sedan,172.4,NaN,four,6989.0
52,mitsubishi,sedan,172.4,ohc,four,8189.0
53,nissan,sedan,NaN,ohc,four,7099.0
54,nissan,sedan,165.3,ohc,four,6649.0
55,nissan,sedan,165.3,ohc,four,6849.0
56,nissan,wagon,170.2,ohc,four,7349.0
57,nissan,sedan,184.6,ohcv,six,13499.0
61,porsche,hardtop,NaN,NaN,six,34028.0
62,porsche,convertible,168.9,ohcf,six,37028.0
66,toyota,hatchback,158.7,ohc,four,5348.0
67,toyota,hatchback,158.7,NaN,four,6338.0
68,toyota,hatchback,158.7,ohc,four,6488.0
69,toyota,wagon,169.7,ohc,four,6918.0
70,toyota,wagon,NaN,NaN,four,7898.0
71,toyota,wagon,169.7,ohc,four,8778.0
79,toyota,wagon,187.8,dohc,six,15750.0
80,volkswagen,sedan,NaN,ohc,four,7775.0
81,volkswagen,sedan,171.7,ohc,four,7975.0
82,volkswagen,sedan,171.7,NaN,four,7995.0
86,volkswagen,sedan,NaN,ohc,four,9995.0
87,volvo,sedan,188.8,NaN,four,12940.0
88,volvo,wagon,188.8,ohc,four,13415.0

In [13]:
df.dropna(subset=['price', 'horsepower'])

KeyError: ['horsepower']

In [14]:
df2 = df.dropna(subset=['price', 'horsepower'])

KeyError: ['horsepower']

In [ ]:
df.shape

(61, 9)

In [15]:
df2.shape

NameError: name 'df2' is not defined

In [16]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [17]:
df.fillna(0)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,0.0,21.0,13495.0
1,alfa-romero,convertible,0.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,0.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,0.0,0.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,0.0,171.7,0,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,0.0,ohc,four,100.0,0.0,9995.0
87,volvo,sedan,104.3,188.8,0,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,0.0,23.0,13415.0

In [18]:
df.fillna(999)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,999.0,21.0,13495.0
1,alfa-romero,convertible,999.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,999.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,999.0,999.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,999.0,171.7,999,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,999.0,ohc,four,100.0,999.0,9995.0
87,volvo,sedan,104.3,188.8,999,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,999.0,23.0,13415.0

In [19]:
df.fillna({'horsepower':100, "wheel-base":np.mean(df['wheel-base'])})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.600000,168.8,dohc,four,100.0,21.0,13495.0
1,alfa-romero,convertible,99.219565,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.500000,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.800000,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.400000,176.6,ohc,five,100.0,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.300000,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,99.219565,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.300000,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.300000,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.300000,188.8,ohc,four,100.0,23.0,13415.0

In [20]:
np.mean(df['wheel-base'])

np.float64(99.2195652173913)

In [21]:
df.fillna({'horsepower':np.mean(df['horsepower']), "wheel-base":np.mean(df['wheel-base'])})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.600000,168.8,dohc,four,108.266667,21.0,13495.0
1,alfa-romero,convertible,99.219565,168.8,dohc,four,111.000000,21.0,16500.0
2,alfa-romero,hatchback,94.500000,171.2,ohcv,six,154.000000,NaN,16500.0
3,audi,sedan,99.800000,176.6,ohc,four,102.000000,24.0,13950.0
4,audi,sedan,99.400000,176.6,ohc,five,108.266667,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.300000,171.7,ohc,four,85.000000,27.0,7975.0
82,volkswagen,sedan,99.219565,171.7,NaN,four,52.000000,37.0,7995.0
86,volkswagen,sedan,97.300000,NaN,ohc,four,100.000000,NaN,9995.0
87,volvo,sedan,104.300000,188.8,NaN,four,114.000000,23.0,12940.0
88,volvo,wagon,104.300000,188.8,ohc,four,108.266667,23.0,13415.0

In [22]:
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [23]:
df.fillna(method='bfill')

<ipython-input-23-b823574c06e2>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,13495.0
1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,24.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,110.0,19.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,188.8,ohc,four,100.0,23.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [24]:
df.fillna(method='ffill')

<ipython-input-24-5c0beae7dc1e>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,102.0,24.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,37.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114.0,23.0,13415.0

In [25]:
df[df.company=='toyota']

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,NaN,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,NaN,four,NaN,31.0,6338.0
68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,NaN,NaN,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,NaN,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [26]:
df[df.company=='toyota'].fillna(method='bfill')

<ipython-input-26-29c7b327e05f>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[df.company=='toyota'].fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,156.0,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [27]:
df[df.company=='toyota']=df[df.company=='toyota'].fillna(method='bfill')

<ipython-input-27-abd51be874e2>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[df.company=='toyota']=df[df.company=='toyota'].fillna(method='bfill')

In [28]:
df[df.company=='toyota']

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,156.0,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [29]:
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [30]:
df.fillna(df.mean())

TypeError: can only concatenate str (not "int") to str

In [31]:
dfh = df[df['body-style']=='hatchback']

In [32]:
dfh

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
16,chevrolet,hatchback,88.4,141.1,l,three,NaN,47.0,5151.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
20,dodge,hatchback,93.7,NaN,ohc,four,68.0,NaN,6229.0
36,mazda,hatchback,93.1,159.1,NaN,four,NaN,NaN,5195.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
39,mazda,hatchback,NaN,NaN,NaN,two,101.0,17.0,11845.0
49,mitsubishi,hatchback,NaN,157.3,ohc,four,NaN,37.0,5389.0
50,mitsubishi,hatchback,93.7,NaN,NaN,four,68.0,31.0,6189.0
63,porsche,hatchback,98.4,175.7,dohcv,eight,NaN,NaN,NaN
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0

In [33]:
dfh.fillna(dfh.mean())

TypeError: can only concatenate str (not "int") to str

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv')
df.head()

   rank  country     density   densityMi    pop2021   area
0     1    Macau  21946.4667  56841.3487    658.394     30
1     2   Monaco  19755.5000  51166.7450     39.511      2
2    28  Burundi    440.3044   1140.3884  12255.433  27834
3     1    Macau  21946.4667  56841.3487    658.394     30
4     2   Monaco  19755.5000  51166.7450     39.511      2

In [39]:
df.dublicated()

AttributeError: 'DataFrame' object has no attribute 'dublicated'

In [34]:
df.shape

(61, 9)

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df.drop_duplicates()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [40]:
df.drop_duplicates(['country'])

KeyError: Index(['country'], dtype='object')

In [41]:
df.drop_duplicates(['country', 'rank'])

KeyError: Index(['rank', 'country'], dtype='object')

In [42]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [43]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [45]:
dict = {'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'eight':8, 'twelve':12}
df['cylinders'] = df['num-of-cylinders'].map(dict)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders
index,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5
...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4

In [46]:
df['price']

index
0     13495.0
1     16500.0
2     16500.0
3     13950.0
4     17450.0
       ...
81     7975.0
82     7995.0
86     9995.0
87    12940.0
88    13415.0
Name: price, Length: 61, dtype: float64

In [49]:
kurs = 10720
df['price_uz'] = df['price'].map(lambda x: x*kurs)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4,143808800.0

In [50]:
df.replace('four',4)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,143808800.0

In [51]:
df.replace('six',6)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4,143808800.0

In [52]:
df.replace(dict)

<ipython-input-52-8aefe9890877>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(dict)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,5,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,143808800.0

In [53]:
df2 = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv", index_col='country')

In [54]:
df2.head()

         rank     density   densityMi    pop2021   area
country
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2
Burundi    28    440.3044   1140.3884  12255.433  27834
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2

In [55]:
df2.rename(index=str.upper)

                  rank     density   densityMi    pop2021     area
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [56]:
df2.rename(index=str.upper, columns=str.upper)

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [57]:
df2.rename(index=str.upper, columns=str.upper, inplace=True)

In [59]:
df2.rename(columns={"pop2021":"population"}, index={"Macau":"Makao"}, inplace=True)

In [61]:
df2

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]